### ISSUE TITLE
different messages to connected clients

### ISSUE THREAD

**Issue by hgbk** [Warfley/LazWebsockets#14]
Though this is not an issue but a question I dare before becoming desperate:
I have a client written in JavaScript and a backend-server written in Lazarus Pascal. The communication is to be done via WebSockets (derived from the chat example). The data to be transferred are coded in JSON. 4 clients are connected to the server.  My question is how to differentiate between the various connections, e.g. to send different messages to each of them? 
p.s.: great stuff, your LazWebsockets!

**Comment by hgbk** [comment]
Though I still don’t know how to identify TWebsocketCommunincator during Connect, I found a workaround  which solves my specific problem:
I identify the TWebsocketCommunincator during the first message received from a specific client and assign it to an array of TWebsocketCommunincator (:= TWebsocketCommunincator(Sender)). So I can send separate messages to the different clients.

**Comment by Warfley** [comment]
This was how it was originally intended to be done. I wanted to keep the library as lightwight as possible, meaning such management functionality needed to be implemented by the user.

That said, as you are not the only one seeking such functionality, and for technical reasons this makes managing the memory (i.e. freeing of `TWebsocketCommunicator` instances) easier, I just added another commit that added such functionality to the `TWebsocketHandler` class. 

See the `broadcastServer` example on how to use it.

**Comment by hgbk** [comment]
Thank you! May I ask you a question?

I have a client written in JavaScript and a backend-server written in Lazarus Pascal. The communication is done via WebSockets (possible thanks to LazWebockets). The data to be transferred are coded in JSON. 4 clients are connected to the server. As an absolute beginner in http/sockets/websockets I have difficulties in understanding how to use the LazWebsockets. Digging in one piece opens 10 more questions for me. In principle the logic of my server is like this:

Code
repeat 
  accept client connection
until 4 clients are connected
repeat
  Code 
  receive data from 1 or more clients (at this point it’s clear whether one or 4 clients are expected to respond)
  Code 
  send data to all clients
until 1 or more clients disconnect
Code 

My problem is how to use the LazWebSockets to send and receive data within my coding rather than integrating the logic in TSocketHandler (which I think would be a problem).

 

I’m sending this via Email because it’s probably not of common interest and I don’t want to offend the rules of the forum.

 

Regards,

Helmut

 

Von: Frederic [mailto:notifications@github.com] 
Gesendet: Montag, 1. März 2021 17:57
An: Warfley/LazWebsockets
Cc: hgbk; State change
Betreff: Re: [Warfley/LazWebsockets] different messages to connected clients (#14)

 

This was how it was originally intended to be done. I wanted to keep the library as lightwight as possible, meaning such management functionality needed to be implemented by the user.

That said, as you are not the only one seeking such functionality, and for technical reasons this makes managing the memory (i.e. freeing of TWebsocketCommunicator instances) easier, I just added another commit that added such functionality to the TWebsocketHandler class.

See the broadcastServer example on how to use it.

**Comment by Warfley** [comment]
So answering this is a little bit complicated (especially via mail), so I created a simple demo code that should have the structure you are seeking for. I hope it is sufficently commented.


With best regards,

Frederic

________________________________
Von: hgbk <notifications@github.com>
Gesendet: Dienstag, 2. März 2021 17:35:30
An: Warfley/LazWebsockets
Cc: Kehrein, Frederic; Comment
Betreff: Re: [Warfley/LazWebsockets] different messages to connected clients (#14)


Thank you! May I ask you a question?

I have a client written in JavaScript and a backend-server written in Lazarus Pascal. The communication is done via WebSockets (possible thanks to LazWebockets). The data to be transferred are coded in JSON. 4 clients are connected to the server. As an absolute beginner in http/sockets/websockets I have difficulties in understanding how to use the LazWebsockets. Digging in one piece opens 10 more questions for me. In principle the logic of my server is like this:

Code
repeat
accept client connection
until 4 clients are connected
repeat
Code
receive data from 1 or more clients (at this point it’s clear whether one or 4 clients are expected to respond)
Code
send data to all clients
until 1 or more clients disconnect
Code

My problem is how to use the LazWebSockets to send and receive data within my coding rather than integrating the logic in TSocketHandler (which I think would be a problem).



I’m sending this via Email because it’s probably not of common interest and I don’t want to offend the rules of the forum.



Regards,

Helmut



Von: Frederic [mailto:notifications@github.com]
Gesendet: Montag, 1. März 2021 17:57
An: Warfley/LazWebsockets
Cc: hgbk; State change
Betreff: Re: [Warfley/LazWebsockets] different messages to connected clients (#14)



This was how it was originally intended to be done. I wanted to keep the library as lightwight as possible, meaning such management functionality needed to be implemented by the user.

That said, as you are not the only one seeking such functionality, and for technical reasons this makes managing the memory (i.e. freeing of TWebsocketCommunicator instances) easier, I just added another commit that added such functionality to the TWebsocketHandler class.

See the broadcastServer example on how to use it.

**Comment by hgbk** [comment]
> So answering this is a little bit complicated (especially via mail), so I created a simple demo code that should have the structure you are seeking for. I hope it is sufficently commented. With best regards,

Sorry for asking again: Where do I find this " simple demo code"?
Regards,
Helmut
